config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :doctors, only: %i[index new show create edit update] do
    resources :procedures, only: %i[show new create]
  end

  # get 'doctors', to: 'doctors#index'
  # get 'doctors/new', to: 'doctors#new'
  # get 'doctors/:id', to: 'doctors#show', as: :doctor
  # post 'doctors', to: 'doctors#create'
  # get  'doctors/:id/edit', to: 'doctors#edit'
  # patch 'doctors/:id', to: 'doctors#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/consultant.rb
class Consultant < ApplicationRecord
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :procedures
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :doctor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.save
    redirect_to doctor_path(@doctor)
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    @doctor.update(doctor_params)
    redirect_to doctors_path(@doctor)
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :speciality)
  end
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
  # index
  def show
    @doctor = Doctor.find(params[:doctor_id])
    @procedures = Procedure.all
  end

  #new procedure innit
  def new
    @doctor = Doctor.find(params[:doctor_id])
    @procedure = Procedure.new
  end

  def create
    @procedure = Procedure.new(procedure_params)
    @doctor = Doctor.find(params[:doctor_id])
    @procedure.doctor = @procedure
    return @procedure unless @procedure.save
  end

  private

  def procedure_params
    params.require(:procedure).permit(:code, :items, :instruments, :description, :doctor_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/constultants_helper.rb
module ConstultantsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/views/doctors/_form.html.erb
<div>
  <%= simple_form_for(@doctor) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :speciality %>
    <%= f.submit %>
  <% end %>
</div>

app/views/doctors/edit.html.erb
<div>
  <%= simple_form_for(@doctor) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :speciality %>
    <%= f.submit %>
  <% end %>
</div>

app/views/doctors/index.html.erb
<div style="text-align:center">
  <h1>Consultants</h1>
  <%= link_to " All Doctors", doctors_path %>

  <ul>
    <% @doctors.each do |doctor| %>
      <li> <%= link_to doctor.first_name, doctor_path(doctor) %> <%= doctor.last_name %>, <%= doctor.speciality %>  </li>
    <% end %>
  </ul>

  <button><p><%= link_to 'Add new Doctor', new_doctor_path %></p></button>
</div>

app/views/doctors/show.html.erb
<h2>Doctors</h2>
  <p> <%= @doctor.first_name %> </p>
  <p> <%= @doctor.last_name %> </p>
  <p> <%= @doctor.speciality %> </p>

<% @doctor.procedures.each do |procedure| %>
  <p><%= procedure.description %></p>
  <p><%= procedure.code %></p>
  <p><%= procedure.items %></p>
  <p><%= procedure.instruments %></p>
<% end %>

<%# would like to render form to add procedure under a doctor%>
<%# <%= render '/procedures/form'  %>


<%= link_to 'back', doctors_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prefcards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/procedures/_form.html.erb
<div>
  <%= simple_form_for [@doctor, @procedure] do |f| %>
    <%= f.input :code %>
    <%= f.input :items %>
    <%= f.input :instruments %>
    <%= f.input :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/procedures/new.html.erb
<%= render 'form' %>

app/views/procedures/show.html.erb
<h1>procedures</h1>
<% @doctor.procedures.each do |procedure|%>
  <%= procedure.code%>
  <%= procedure.items %>
  <%= procedure.instruments %>
  <%= procedure.description%>
<%end%>